    <!-- Footer -->
         <footer>
                 <div class="container">
                             <div class="footer-content">
                                             <div class="footer-about">
                                                                 <div class="footer-logo">KNUST<span>Intern</span></div>
                                                                                     <p>Portfolio website showcasing my mini internship experience at the KNUST Computer Hardware Unit.</p>
                                                                                                     </div>
                                                                                                                     <div class="footer-links">
                                                                                                                                         <h4>Quick Links</h4>
                                                                                                                                                             <a href="index.php">Home</a>
                                                                                                                                                                                 <a href="about.php">About</a>
                                                                                                                                                                                                     <a href="internship.php">Internship</a>
                                                                                                                                                                                                                         <a href="gallery.php">Gallery</a>
                                                                                                                                                                                                                                             <a href="contact.php">Contact</a>
                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                             <div class="footer-social">
                                                                                                                                                                                                                                                                                                 <h4>Connect With Me</h4>
                                                                                                                                                                                                                                                                                                                     <div class="social-links">
                                                                                                                                                                                                                                                                                                                                             <a href="#"><i class="fab fa-linkedin-in"></i></a>
                                                                                                                                                                                                                                                                                                                                                                     <a href="#"><i class="fab fa-twitter"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                             <a href="#"><i class="fab fa-github"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                     <a href="#"><i class="fab fa-instagram"></i></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="copyright">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p>&copy; <?php echo date('Y'); ?> Zaidan Yakubu. All Rights Reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </footer>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <script src="assets/js/script.js"></script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </html>