<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title><?php echo isset($page_title) ? $page_title : 'KNUST Internship Portfolio'; ?></title>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                    <link rel="stylesheet" href="assets/css/style.css">
                    </head>
                    <body>
                        <!-- Navigation -->
                            <nav id="navbar">
                                    <div class="container nav-container">
                                                <a href="index.php" class="logo">KNUST<span>Intern</span></a>
                                                            <ul class="nav-links">
                                                                            <li><a href="index.php">Home</a></li>
                                                                                            <li><a href="about.php">About</a></li>
                                                                                                            <li><a href="internship.php">Internship</a></li>
                                                                                                                            <li><a href="gallery.php">Gallery</a></li>
                                                                                                                                            <li><a href="contact.php">Contact</a></li>
                                                                                                                                                            
                                                                                                                                                                            <?php if(isset($_SESSION['admin_logged_in'])): ?>
                                                                                                                                                                                                <li><a href="admin/dashboard.php">Admin</a></li>
                                                                                                                                                                                                                    <li><a href="admin/logout.php">Logout</a></li>
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    <?php elseif(isLoggedIn()): ?>
                                                                                                                                                                                                                                                                        <?php $currentUser = getCurrentUser(); ?>
                                                                                                                                                                                                                                                                                            <li class="dropdown">
                                                                                                                                                                                                                                                                                                                    <a href="#" class="dropdown-toggle">
                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-user"></i> <?php echo $currentUser['full_name']; ?>
                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                <ul class="dropdown-menu">
                                                                                                                                                                                                                                                                                                                                                                                                                            <li><a href="member/dashboard.php">Dashboard</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li><a href="member/profile.php">My Profile</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li><a href="member/logout.php">Logout</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li><a href="register.php">Register</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li><a href="login.php">Login</a></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="mobile-menu">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-bars"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if(isset($_SESSION['message'])): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="alert <?php echo $_SESSION['message_type']; ?>">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo $_SESSION['message']; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                unset($_SESSION['message']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                unset($_SESSION['message_type']);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>