<?php
// admin/dashboard.php
$base_url='../';
include '../includes/header.php';

// Check if admin is logged in
if (!isset($_SESSION['admin_logged_in'])) {
    header("Location: login.php");
        exit();
        }

        // Get statistics
        $contacts_count = $conn->query("SELECT COUNT(*) as count FROM contacts")->fetch_assoc()['count'];
        $members_count = $conn->query("SELECT COUNT(*) as count FROM members")->fetch_assoc()['count'];
        $recent_contacts = $conn->query("SELECT * FROM contacts ORDER BY created_at DESC LIMIT 5");
        ?>

        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Admin Dashboard | KNUST Internship</title>
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                            <link rel="stylesheet" href="../assets/css/style.css">
                            </head>
                            <body>
                                <?php include '../includes/header.php'; ?>

                                    <div class="admin-container">
                                            <div class="admin-header">
                                                        <h1><i class="fas fa-tachometer-alt"></i> Admin Dashboard</h1>
                                                                    <p>Welcome, <?php echo $_SESSION['admin_username']; ?>!</p>
                                                                            </div>

                                                                                    <div class="admin-nav">
                                                                                                <ul>
                                                                                                                <li><a href="dashboard.php" class="active"><i class="fas fa-tachometer-alt"></i> Dashboard</a></li>
                                                                                                                                <li><a href="manage-content.php"><i class="fas fa-edit"></i> Manage Content</a></li>
                                                                                                                                                <li><a href="logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                                                                                                                                                            </ul>
                                                                                                                                                                    </div>

                                                                                                                                                                            <div class="dashboard-cards">
                                                                                                                                                                                        <div class="dashboard-card">
                                                                                                                                                                                                        <i class="fas fa-envelope"></i>
                                                                                                                                                                                                                        <h3><?php echo $contacts_count; ?></h3>
                                                                                                                                                                                                                                        <p>Total Messages</p>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                <div class="dashboard-card">
                                                                                                                                                                                                                                                                                <i class="fas fa-users"></i>
                                                                                                                                                                                                                                                                                                <h3><?php echo $members_count; ?></h3>
                                                                                                                                                                                                                                                                                                                <p>Registered Members</p>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                        <div class="dashboard-card">
                                                                                                                                                                                                                                                                                                                                                        <i class="fas fa-user"></i>
                                                                                                                                                                                                                                                                                                                                                                        <h3>1</h3>
                                                                                                                                                                                                                                                                                                                                                                                        <p>Admin Users</p>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                <div class="dashboard-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-calendar"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>8</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Weeks Internship</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="table-container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 style="padding: 20px; margin: 0;">Recent Messages</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Name</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Email</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Subject</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <th>Date</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php while($contact = $recent_contacts->fetch_assoc()): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo htmlspecialchars($contact['name']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><?php echo htmlspecialchars($contact['email']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td><?php echo htmlspecialchars($contact['subject']); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td><?php echo date('M j, Y', strtotime($contact['created_at'])); ?></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endwhile; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php if ($contacts_count == 0): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td colspan="4" style="text-align: center;">No messages yet</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php include '../includes/footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>