<?php
// admin/login.php
include '../includes/config.php';

// Redirect if already logged in
if (isset($_SESSION['admin_logged_in'])) {
    header("Location: dashboard.php");
        exit();
        }

        // Process login
        if ($_SERVER['REQUEST_METHOD'] == 'POST') {
            $username = $conn->real_escape_string($_POST['username']);
                $password = $_POST['password'];
                    
                        $sql = "SELECT * FROM admin_users WHERE username = '$username'";
                            $result = $conn->query($sql);
                                
                                    if ($result->num_rows == 1) {
                                            $admin = $result->fetch_assoc();
                                                    
                                                            if (password_verify($password, $admin['password'])) {
                                                                        $_SESSION['admin_logged_in'] = true;
                                                                                    $_SESSION['admin_username'] = $username;
                                                                                                $_SESSION['message'] = "Login successful!";
                                                                                                            $_SESSION['message_type'] = "success";
                                                                                                                        header("Location: dashboard.php");
                                                                                                                                    exit();
                                                                                                                                            } else {
                                                                                                                                                        $error = "Invalid password!";
                                                                                                                                                                }
                                                                                                                                                                    } else {
                                                                                                                                                                            $error = "Invalid username!";
                                                                                                                                                                                }
                                                                                                                                                                                }
                                                                                                                                                                                ?>

                                                                                                                                                                                <!DOCTYPE html>
                                                                                                                                                                                <html lang="en">
                                                                                                                                                                                <head>
                                                                                                                                                                                    <meta charset="UTF-8">
                                                                                                                                                                                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                                                                                                                            <title>Admin Login | KNUST Internship</title>
                                                                                                                                                                                                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                                                                                                                                                                                                    <link rel="stylesheet" href="../assets/css/style.css">
                                                                                                                                                                                                    </head>
                                                                                                                                                                                                    <body>
                                                                                                                                                                                                        <div class="login-container">
                                                                                                                                                                                                                <h2><i class="fas fa-lock"></i> Admin Login</h2>
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                <?php if (isset($error)): ?>
                                                                                                                                                                                                                                            <div class="alert error"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    <form action="login.php" method="POST">
                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                                <label for="username">Username</label>
                                                                                                                                                                                                                                                                                                                <input type="text" id="username" name="username" class="form-control" required>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                        <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                        <label for="password">Password</label>
                                                                                                                                                                                                                                                                                                                                                                        <input type="password" id="password" name="password" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn">Login</button>
                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="text-align: center; margin-top: 20px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="../index.php" style="color: var(--primary);">← Back to Website</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style="margin-top: 30px; padding: 15px; background: #f8f9fa; border-radius: 5px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="font-size: 0.9rem; color: var(--gray); text-align: center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Default Credentials:</strong><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Username: admin<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Password: admin123
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>