<?php
// about.php
$page_title = "About Me | KNUST Internship Portfolio";
include 'includes/config.php';
include 'includes/header.php';
?>

<!-- About Section -->
<section id="about">
    <div class="container">
            <div class="section-title">
                        <h2>About Me</h2>
                                </div>
                                        <div class="about-content">
                                                    <div class="about-text">
                                                                    <h3>Computer Science Student at KNUST</h3>
                                                                                    <p>I am a passionate and dedicated Computer Science student at Kwame Nkrumah University of Science and Technology (KNUST) with a keen interest in computer hardware, system administration, and network infrastructure.</p>
                                                                                                    <p>During my mini internship at the KNUST Computer Hardware Unit, I gained hands-on experience in computer assembly, troubleshooting, maintenance, and network setup. This experience has strengthened my technical skills and provided valuable insights into real-world IT operations.</p>
                                                                                                                    <p>My academic background includes courses in Computer Architecture, Networking, Operating Systems, and Database Management, which provided me with a solid foundation for my internship experience.</p>
                                                                                                                                    <p>I am eager to apply the knowledge and skills acquired during my internship to future projects and career opportunities in the technology field.</p>
                                                                                                                                                    
                                                                                                                                                                    <h3>Education</h3>
                                                                                                                                                                                    <p><strong>Bachelor of Science in Computer Science</strong><br>
                                                                                                                                                                                                    Kwame Nkrumah University of Science and Technology (KNUST)<br>
                                                                                                                                                                                                                    Expected Graduation: 2024</p>
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    <h3>Certifications</h3>
                                                                                                                                                                                                                                                                    <ul>
                                                                                                                                                                                                                                                                                        <li>KNUST Computer Hardware Internship Certificate</li>
                                                                                                                                                                                                                                                                                                            <li>CompTIA A+ (In Progress)</li>
                                                                                                                                                                                                                                                                                                                                <li>Microsoft Technology Associate (MTA)</li>
                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                <a href="contact.php" class="btn">Get In Touch</a>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div class="about-image">
                                                                                                                                                                                                                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="About Image">
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                include 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                ?>