<?php
// contact.php
$page_title = "Contact | KNUST Internship Portfolio";
include 'includes/config.php';
include 'includes/header.php';

// Process form submission
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $name = $conn->real_escape_string($_POST['name']);
        $email = $conn->real_escape_string($_POST['email']);
            $subject = $conn->real_escape_string($_POST['subject']);
                $message = $conn->real_escape_string($_POST['message']);
                    
                        // Insert into database
                            $sql = "INSERT INTO contacts (name, email, subject, message) VALUES ('$name', '$email', '$subject', '$message')";
                                
                                    if ($conn->query($sql) === TRUE) {
                                            $_SESSION['message'] = "Thank you for your message! I will get back to you soon.";
                                                    $_SESSION['message_type'] = "success";
                                                            
                                                                    // Redirect to prevent form resubmission
                                                                            header("Location: contact.php");
                                                                                    exit();
                                                                                        } else {
                                                                                                $_SESSION['message'] = "Sorry, there was an error sending your message. Please try again.";
                                                                                                        $_SESSION['message_type'] = "error";
                                                                                                            }
                                                                                                            }
                                                                                                            ?>

                                                                                                            <!-- Contact Section -->
                                                                                                            <section id="contact">
                                                                                                                <div class="container">
                                                                                                                        <div class="section-title">
                                                                                                                                    <h2>Contact Me</h2>
                                                                                                                                            </div>
                                                                                                                                                    <div class="contact-container">
                                                                                                                                                                <div class="contact-info">
                                                                                                                                                                                <h3>Get In Touch</h3>
                                                                                                                                                                                                <p>Feel free to reach out if you have any questions about my internship experience or if you'd like to discuss potential opportunities.</p>
                                                                                                                                                                                                                <div class="contact-item">
                                                                                                                                                                                                                                    <i class="fas fa-envelope"></i>
                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                <h4>Email</h4>
                                                                                                                                                                                                                                                                                                        <p>zaiyark@gmail.com</p>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                            <div class="contact-item">
                                                                                                                                                                                                                                                                                                                                                                                <i class="fas fa-phone"></i>
                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                            <h4>Phone</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>+233 55 848 9313</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="contact-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="fas fa-map-marker-alt"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h4>Location</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Kumasi, Ghana</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="contact-form">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form action="contact.php" method="POST" id="contactForm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label for="name">Full Name</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" id="name" name="name" class="form-control" placeholder="Your Name" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label for="email">Email Address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="email" id="email" name="email" class="form-control" placeholder="Your Email" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label for="subject">Subject</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label for="message">Message</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <textarea id="message" name="message" class="form-control" placeholder="Your Message" required></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn">Send Message</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        include 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>