<?php
// forgot-password.php
$page_title = "Forgot Password | KNUST Internship Portfolio";
include 'includes/config.php';

// Simple forgot password placeholder
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $email = $conn->real_escape_string($_POST['email']);
        
            // Check if email exists
                $result = $conn->query("SELECT * FROM members WHERE email = '$email'");
                    
                        if ($result->num_rows == 1) {
                                $_SESSION['message'] = "Password reset instructions have been sent to your email.";
                                        $_SESSION['message_type'] = "success";
                                                header("Location: login.php");
                                                        exit();
                                                            } else {
                                                                    $error = "No account found with this email address!";
                                                                        }
                                                                        }
                                                                        ?>

                                                                        <!DOCTYPE html>
                                                                        <html lang="en">
                                                                        <head>
                                                                            <meta charset="UTF-8">
                                                                                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                                                                                    <title><?php echo $page_title; ?></title>
                                                                                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                                                                                            <link rel="stylesheet" href="assets/css/style.css">
                                                                                            </head>
                                                                                            <body>
                                                                                                <?php include 'includes/header.php'; ?>

                                                                                                    <section class="auth-section">
                                                                                                            <div class="container">
                                                                                                                        <div class="auth-container" style="max-width: 500px; margin: 0 auto;">
                                                                                                                                        <div class="auth-form">
                                                                                                                                                            <h2><i class="fas fa-key"></i> Forgot Password</h2>
                                                                                                                                                                                <p>Enter your email address to reset your password</p>
                                                                                                                                                                                                    
                                                                                                                                                                                                                        <?php if (isset($error)): ?>
                                                                                                                                                                                                                                                <div class="alert error"><?php echo $error; ?></div>
                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            <form action="forgot-password.php" method="POST">
                                                                                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                <label for="email">Email Address *</label>
                                                                                                                                                                                                                                                                                                                                                                                            <input type="email" id="email" name="email" class="form-control" required>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" class="btn btn-primary btn-block">Reset Password</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="auth-links">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Remember your password? <a href="login.php">Login here</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>Don't have an account? <a href="register.php">Register here</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php include 'includes/footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>