<?php
// gallery.php
$page_title = "Gallery | KNUST Internship Portfolio";
include 'includes/config.php';
include 'includes/header.php';
?>

<!-- Gallery Section -->
<section id="gallery" class="gallery">
    <div class="container">
            <div class="section-title">
                        <h2>Internship Gallery</h2>
                                </div>
                                        <div class="gallery-container">
                                                    <div class="gallery-item">
                                                                    <img src="https://images.unsplash.com/photo-1581094794329-cd0adaa10d5f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Computer Assembly">
                                                                                    <div class="gallery-overlay">
                                                                                                        <i class="fas fa-search-plus"></i>
                                                                                                                        </div>
                                                                                                                                    </div>
                                                                                                                                                <div class="gallery-item">
                                                                                                                                                                <img src="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Hardware Troubleshooting">
                                                                                                                                                                                <div class="gallery-overlay">
                                                                                                                                                                                                    <i class="fas fa-search-plus"></i>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                            <div class="gallery-item">
                                                                                                                                                                                                                                                            <img src="https://images.unsplash.com/photo-1544197150-b99a580bb7a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Network Setup">
                                                                                                                                                                                                                                                                            <div class="gallery-overlay">
                                                                                                                                                                                                                                                                                                <i class="fas fa-search-plus"></i>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                        <div class="gallery-item">
                                                                                                                                                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1541140532154-b024d705b90a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Technical Support">
                                                                                                                                                                                                                                                                                                                                                                        <div class="gallery-overlay">
                                                                                                                                                                                                                                                                                                                                                                                            <i class="fas fa-search-plus"></i>
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="gallery-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com/photo-1562408590-e32931084e23?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Computer Lab">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="gallery-overlay">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <i class="fas fa-search-plus"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="gallery-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <img src="https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Server Room">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="gallery-overlay">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="fas fa-search-plus"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            include 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>