<?php
// index.php
$page_title = "KNUST Computer Hardware Internship | Student Portfolio";
include 'includes/config.php';
include 'includes/header.php';
?>

<!-- Header -->
<header id="home">
    <div class="container header-content">
            <div class="profile-img">
                        <img src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80" alt="Student Profile">
                                </div>
                                        <h1>Zaidan Yakubu</h1>
                                                <p>Computer Science Student | KNUST Computer Hardware Unit Intern</p>
                                                        <a href="internship.php" class="btn">View Internship Experience</a>
                                                            </div>
                                                            </header>

                                                            <!-- About Section -->
                                                            <section id="about">
                                                                <div class="container">
                                                                        <div class="section-title">
                                                                                    <h2>About Me</h2>
                                                                                            </div>
                                                                                                    <div class="about-content">
                                                                                                                <div class="about-text">
                                                                                                                                <h3>Computer Science Student at KNUST</h3>
                                                                                                                                                <p>I am a passionate and dedicated Computer Science student at Kwame Nkrumah University of Science and Technology (KNUST) with a keen interest in computer hardware, system administration, and network infrastructure.</p>
                                                                                                                                                                <p>During my mini internship at the KNUST Computer Hardware Unit, I gained hands-on experience in computer assembly, troubleshooting, maintenance, and network setup. This experience has strengthened my technical skills and provided valuable insights into real-world IT operations.</p>
                                                                                                                                                                                <a href="about.php" class="btn">Learn More About Me</a>
                                                                                                                                                                                            </div>
                                                                                                                                                                                                        <div class="about-image">
                                                                                                                                                                                                                        <img src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="About Image">
                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                <!-- Skills Section -->
                                                                                                                                                                                                                                                <section id="skills">
                                                                                                                                                                                                                                                    <div class="container">
                                                                                                                                                                                                                                                            <div class="section-title">
                                                                                                                                                                                                                                                                        <h2>Skills Acquired</h2>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                        <div class="skills-container">
                                                                                                                                                                                                                                                                                                    <div class="skill-card">
                                                                                                                                                                                                                                                                                                                    <i class="fas fa-desktop"></i>
                                                                                                                                                                                                                                                                                                                                    <h3>Computer Assembly</h3>
                                                                                                                                                                                                                                                                                                                                                    <p>Expertise in assembling desktop computers from individual components and ensuring compatibility.</p>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                            <div class="skill-card">
                                                                                                                                                                                                                                                                                                                                                                                            <i class="fas fa-tools"></i>
                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Hardware Troubleshooting</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Ability to diagnose and resolve various hardware issues efficiently and effectively.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="skill-card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <i class="fas fa-network-wired"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>Networking</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Experience in setting up and configuring local area networks and network devices.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            include 'includes/footer.php';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ?>