<?php
// member/settings.php
$page_title = "Settings | KNUST Internship";
include '../includes/config.php';

// Check if member is logged in
if (!isLoggedIn()) {
    header("Location: ../login.php");
        exit();
        }

        $currentUser = getCurrentUser();
        ?>

        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title><?php echo $page_title; ?></title>
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
                            <link rel="stylesheet" href="../assets/css/style.css">
                            </head>
                            <body>
                                <?php include '../includes/header.php'; ?>

                                    <div class="member-container">
                                            <div class="member-header">
                                                        <div class="container">
                                                                        <div class="member-welcome">
                                                                                            <h1><i class="fas fa-cog"></i> Settings</h1>
                                                                                                                <p>Manage your account settings</p>
                                                                                                                                </div>
                                                                                                                                            </div>
                                                                                                                                                    </div>

                                                                                                                                                            <div class="container">
                                                                                                                                                                        <div class="member-nav">
                                                                                                                                                                                        <ul>
                                                                                                                                                                                                            <li><a href="dashboard.php"><i class="fas fa-tachometer-alt"></i> Dashboard</a></li>
                                                                                                                                                                                                                                <li><a href="profile.php"><i class="fas fa-user-edit"></i> My Profile</a></li>
                                                                                                                                                                                                                                                    <li><a href="settings.php" class="active"><i class="fas fa-cog"></i> Settings</a></li>
                                                                                                                                                                                                                                                                        <li><a href="logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                <div class="settings-container">
                                                                                                                                                                                                                                                                                                                                <div class="settings-section">
                                                                                                                                                                                                                                                                                                                                                    <h3><i class="fas fa-user-shield"></i> Account Security</h3>
                                                                                                                                                                                                                                                                                                                                                                        <div class="settings-content">
                                                                                                                                                                                                                                                                                                                                                                                                <p>Change your password and manage account security settings.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="../forgot-password.php" class="btn btn-secondary">Change Password</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="settings-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3><i class="fas fa-bell"></i> Notifications</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="settings-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Manage your email notification preferences.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="setting-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label class="switch">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input type="checkbox" checked>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="slider"></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Email notifications</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="settings-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3><i class="fas fa-info-circle"></i> Account Information</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="settings-content">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="info-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Member Since:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span><?php echo date('F j, Y', strtotime($currentUser['created_at'])); ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="info-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Student ID:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span><?php echo $currentUser['student_id']; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="info-item">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Email:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span><?php echo $currentUser['email']; ?></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php include '../includes/footer.php'; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>